version = 0.1

[default.deploy.parameters]
stack_name = "kalshi-dashboard-api"
region = "us-east-1"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-4rdxmnrlyr8x"
s3_prefix = "kalshi-dashboard-api"
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"
confirm_changeset = false
disable_rollback = false
parameter_overrides = "PortfolioFetcherLayerArn=arn:aws:lambda:us-east-1:355149669325:layer:production-kalshi-portfolio-fetcher:33 TISVpcSubnets=subnet-0ba02a0291289ed61,subnet-00f42ffa626fb65bc TISVpcSecurityGroups=sg-07bca88870ac173f8"
